services:
  qbittorrent-nox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qbittorrent-nox
    environment:
      - QBT_LEGAL_NOTICE=${QBT_LEGAL_NOTICE}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}/tcp"
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/downloads
    restart: unless-stopped
